name: Feature Request
description: Suggest an idea for improving SmokeLog
title: "[Feature] "
labels: ["enhancement"]
assignees: ["GarlicRot"]
body:
  - type: markdown
    attributes:
      value: "## Feature Request"
  - type: textarea
    id: description
    attributes:
      label: Describe the Feature
      description: A clear and concise description of what you want to happen.
      placeholder: "I’d like to export my session data as a CSV file..."
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Solved
      description: What problem does this feature solve?
      placeholder: "I need to analyze my data in Excel."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you’ve considered?
      placeholder: "I tried copying the data manually, but it’s too time-consuming."
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "This would be great for power users..."
