name: General Feedback
description: Share general feedback or questions about SmokeLog
title: "[Feedback] "
labels: ["question"]
assignees: ["GarlicRot"]
body:
  - type: markdown
    attributes:
      value: "## General Feedback"
  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: Share your thoughts, questions, or suggestions.
      placeholder: "I love the dashboard, but I have a question about session tracking..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots to support your feedback.
      placeholder: "Here’s a screenshot of the dashboard..."
